---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-demo-app
  name: gitops-demo-app
  namespace: app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
      - image: ghcr.io/zaap59/gitops-demo-app:v0.2.3
        name: gitops-demo-app
